// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2026, 6:14:24 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/plugins/**/*.{js,ts,mjs}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/composables/**/*.{js,ts,mjs}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/utils/**/*.{js,ts,mjs}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/app.config.{js,ts,mjs}","/Users/oniolajumoke/portfolio2.0/prolajumokeoni.github.io/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;